// <auto-generated />
using ActividadEvaluableUT8RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActividadEvaluableUT8RazorPages.Migrations
{
    [DbContext(typeof(ActividadEvaluableUT8RazorPagesContext))]
    [Migration("20240314003849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActividadEvaluableUT8RazorPages.Models.Creature", b =>
                {
                    b.Property<int>("creature_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("creature_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("logia_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("creature_id");

                    b.HasIndex("logia_id");

                    b.ToTable("Creature");
                });

            modelBuilder.Entity("ActividadEvaluableUT8RazorPages.Models.Logia", b =>
                {
                    b.Property<int>("logia_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logia_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("logia_id");

                    b.ToTable("Logia");
                });

            modelBuilder.Entity("ActividadEvaluableUT8RazorPages.Models.Mason", b =>
                {
                    b.Property<int>("masone_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("masone_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("logia_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("masone_id");

                    b.HasIndex("logia_id");

                    b.ToTable("Mason");
                });

            modelBuilder.Entity("ActividadEvaluableUT8RazorPages.Models.Creature", b =>
                {
                    b.HasOne("ActividadEvaluableUT8RazorPages.Models.Logia", "Logia")
                        .WithMany()
                        .HasForeignKey("logia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logia");
                });

            modelBuilder.Entity("ActividadEvaluableUT8RazorPages.Models.Mason", b =>
                {
                    b.HasOne("ActividadEvaluableUT8RazorPages.Models.Logia", "Logia")
                        .WithMany()
                        .HasForeignKey("logia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logia");
                });
#pragma warning restore 612, 618
        }
    }
}
